name: CI
on:
  push:
    branches:
      - main
    tags:
      - v*
  pull_request:

jobs:
  lintrunner:
    runs-on: ubuntu-latest
    name: Test the action
    steps:
      - uses: actions/checkout@v3
      - uses: justinchuby/lintrunner-action@main
        with:
          publish_code_scanning: true
          verbose: false
